spring.application.name=processing-service
server.port=8081

sensor.queue = sensor.events

spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${SPRING_ACTIVEMQ_USER:admin}
spring.activemq.password=${SPRING_ACTIVEMQ_PASSWORD:admin}
spring.jms.pub-sub-domain=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hacksauce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

simulator.base-url=http://localhost:8080