spring.application.name=processing-service

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

spring.datasource.url=jdbc:postgresql://localhost:5432/hacksauce
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

simulator.base-url=http://localhost:8080